name: Build and Push Docker

on:
  push:
    tags:
      - '*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # Dockerビルド環境をセットアップする
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # GitHub Packagesにログインする
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # JARファイルをビルドする
      - name: Build JAR
        run: ./gradlew jar
      # イメージをビルドしてpushする
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/java:${{ github.ref_name }}